name: 'Test message echo once'
description: 'Test message'
author: 'mllano'
inputs:
  message:
    description: "Message to echo"
    required: true
runs:
  using: "composite"
  steps:
    - name: Echo once
      shell: bash
      run: echo "${{ inputs.message }}"