name: 'Test message echo'
description: 'Test message'
author: 'mllano'
inputs:
  message:
    description: "Message to echo"
    required: true
runs:
  using: "composite"
  steps:
    - name: Symlink current action repo
      env:
        action_path: ${{ github.action_path }}
      run: ln -fs ${{ env.action_path }}/.. .github/.action_repo.my-cool-repo
      shell: bash
    - uses: ./.github/.action_repo.my-cool-repo/echo-once
      with:
        message: "${{ inputs.message }}"
    - name: Unlink the action repository
      run: rm -f .github/.action_repo.my-cool-repo
      shell: bash