name: Test workflow

on:
  pull_request

jobs:
  test-job:
    runs-on: ubuntu-20.04
    steps:

      - name: checkout git repo
        uses: actions/checkout@v2

      - name: read config
        shell: bash
        run: echo "Hello it ran!"
