name: Check test 1

on:
  check_run:
    types: [completed]

jobs:
  other-job:
    runs-on: ubuntu-20.04
    steps:
      - name: test echo
        shell: bash
        run: echo "Is running now"

      - name: data
        run: echo "${{toJson(github)}}"
        