name: Check test 1

on:
  workflow_run:
    workflows: [Test workflow]
    types:
      - completed

jobs:
  other-job:
    runs-on: ubuntu-20.04
    steps:

      - name: test echo
        shell: bash
        run: echo "Is running now"

      - name: data
        run: echo "${{toJson(github)}}"
      
      - name: event
        run: echo "${{toJson(github.event.workflow_run)}}"
        
      - name: context
        run: echo "${{toJson(context.payload.workflow_run)}}"